export const comparisonMessages = [
  { id: 1, type: 'add', message: 'Found new line in section 1', icon: 'plus', delay: 2000 },
  { id: 2, type: 'remove', message: 'Removed line from section 2', icon: 'minus', delay: 4000 },
  { id: 3, type: 'modify', message: 'Modified content in paragraph 3', icon: 'edit', delay: 6000 },
  { id: 4, type: 'add', message: 'Found new section: Introduction', icon: 'file-plus', delay: 8000 },
  { id: 5, type: 'remove', message: 'Removed section: Deprecated Info', icon: 'file-minus', delay: 10000 },
  { id: 6, type: 'match', message: 'Matched 15 identical lines', icon: 'check', delay: 12000 },
  { id: 7, type: 'add', message: 'Found 3 new lines in section 4', icon: 'plus-circle', delay: 15000 },
  { id: 8, type: 'remove', message: 'Removed 2 lines from footer', icon: 'minus-circle', delay: 18000 },
  { id: 9, type: 'modify', message: 'Updated heading formatting', icon: 'type', delay: 21000 },
  { id: 10, type: 'add', message: 'Found new section: Conclusion', icon: 'file-plus', delay: 24000 },
  { id: 11, type: 'match', message: 'Comparing metadata...', icon: 'scan', delay: 27000 },
  { id: 12, type: 'modify', message: 'Detected spacing changes', icon: 'align-left', delay: 30000 },
  { id: 13, type: 'add', message: 'Found 5 new paragraphs', icon: 'file-text', delay: 33000 },
  { id: 14, type: 'remove', message: 'Removed outdated references', icon: 'x-circle', delay: 36000 },
  { id: 15, type: 'match', message: 'Analyzing structure...', icon: 'layers', delay: 39000 },
  { id: 16, type: 'modify', message: 'Updated list formatting', icon: 'list', delay: 42000 },
  { id: 17, type: 'add', message: 'Found new code blocks', icon: 'code', delay: 45000 },
  { id: 18, type: 'match', message: 'Comparing line by line...', icon: 'git-compare', delay: 48000 },
  { id: 19, type: 'remove', message: 'Removed duplicate content', icon: 'copy-x', delay: 51000 },
  { id: 20, type: 'match', message: 'Finalizing comparison...', icon: 'check-circle', delay: 54000 },
];
 
export const dummyResult = {
  totalLines: 247,
  addedLines: 34,
  removedLines: 18,
  modifiedLines: 12,
  addedSections: 2,
  removedSections: 1,
  matchedLines: 183,
  similarityScore: 85,
  comparisonTime: '60.2s',
};