import os
import asyncio
import numpy as np
import pandas as pd
from src.models import *
from typing import List, Tuple
from config.config import Config
from openpyxl import load_workbook
from deepeval.models import AzureOpenAIModel
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from src.utils_helper import timing_decorator
from src.adapters.azure_openai import batch_client
from src.prompts.system import get_prompt_template
from src.adapters.logger import log_with_span
from src.adapters.azure_document_intelligence import document_intelligence

# Initialize the Azure OpenAI model used for text generation and JSON extraction
if Config.AZURE_OPENAI_KEY:
    model = AzureOpenAIModel(
        model_name=Config.GPT_GENERATION_4O_MODEL,
        deployment_name=Config.GPT_GENERATION_4O_MODEL,
        azure_openai_api_key=Config.AZURE_OPENAI_KEY,
        openai_api_version=Config.AZURE_OPENAI_VERSION,
        azure_endpoint=Config.AZURE_OPENAI_ENDPOINT,
        temperature=0
    )
else:
    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(),
        "https://cognitiveservices.azure.com/.default"
    )
    model = AzureOpenAIModel(
        model_name=Config.GPT_GENERATION_4O_MODEL,
        deployment_name=Config.GPT_GENERATION_4O_MODEL,
        azure_ad_token_provider=token_provider,
        openai_api_version=Config.AZURE_OPENAI_VERSION,
        azure_endpoint=Config.AZURE_OPENAI_ENDPOINT,
        temperature=0
    )


@timing_decorator
async def extract_pdf_pages(pdf_path: str, mode ="hybrid", azure_model = "prebuilt-document") -> PDFTextPages:
    """
    Extract text content from all pages of a PDF asynchronously.

    Uses Azure Document Intelligence API to extract structured text
    from each page of a given PDF document. This function runs in a 
    background thread to avoid blocking the event loop.

    Args:
        pdf_path (str): The full file path of the PDF document to process.

    Returns:
        PDFTextPages: A Pydantic model containing a list of extracted page texts.

    Raises:
        Exception: If the PDF extraction fails or an error occurs in the document API.
    """
    try:
        # Run extraction in a background thread (since I/O is blocking)
        pages_result = await document_intelligence.extract_text_from_pdf_combined(pdf_path, mode, azure_model)
        

        # Collect all text content from extracted page objects
        pages_text = [page.content for page in pages_result.pages]
        return PDFTextPages(pages=pages_text)

    except Exception as e:
        log_with_span(
            "PDF extraction failed",
            "PdfExtractionError",
            "error",
            log_extra={
                "service_name": "extract pdf pages",
                "input": pdf_path,
                "status": "Failed",
                "error": str(e)
            }
        )
        raise


async def identify_index_pages(pages: List[str]) -> IndexPages:
    """
    Identify index or table-of-contents pages in a PDF using an LLM.

    This function sends the first few pages of the document to the LLM
    with a specific system and user prompt to determine which pages 
    contain the table of contents or index section.

    Args:
        pages (List[str]): List of text content for each PDF page.

    Returns:
        tuple:
            - IndexPages: Object containing start and end page numbers of the index.
            - int: Number of input tokens consumed by the model.
            - int: Number of output tokens generated by the model.
            - str: Model name used for processing.

    Raises:
        Exception: If the LLM call or JSON parsing fails.
    """
    try:
        # Prepare the system and user prompts for the model
        system_prompt = get_prompt_template('index_page_identification_prompt.jinja2').render()
        user_prompt = f"Here are the document pages to analyze: {''.join(pages[:20])}"
    
        # Call Azure OpenAI model to process prompt and extract structured output
        response = await batch_client._process_single_request(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            json_mode=True,
            model=Config.GPT_GENERATION_4i,
            convert_to_json=True
        )

        # Parse structured JSON response
        data = response.content
        

        # Return identified index range and token statistics
        return (
            IndexPages(start_page=data['page'][0], end_page=data['page'][1]),
            response.input_tokens,
            response.output_tokens,
            response.model
        )

    except Exception as e:
        log_with_span(
            "Index page identification failed",
            "IndexPageExtractionError",
            "error",
            log_extra={
                "service_name": "index identification",
                "input": len(pages),
                "status": "Failed",
                "error": str(e)
            }
        )      
        raise


async def extract_sections(pages: List[str], index: IndexPages) -> SectionExtraction:
    """
    Extract section information from a subset of PDF pages using an LLM.

    The function uses the section prompt template to analyze text content
    between the identified index pages and extract hierarchical section headers.

    Args:
        pages (List[str]): List of text content for all PDF pages.
        index (IndexPages): Start and end page range of the document index.

    Returns:
        tuple:
            - SectionExtraction: Object containing the structured section hierarchy.
            - int: Number of input tokens consumed by the model.
            - int: Number of output tokens generated by the model.
            - str: Model name used for processing.

    Raises:
        Exception: If the LLM extraction process or JSON parsing fails.
    """
    try:
        # Load the Jinja2 template for section extraction
        system_prompt = get_prompt_template('section_prompt.jinja2').render()

        # Select subset of pages within the index page range
        pages_subset = pages[index.start_page - 1:index.end_page]
        user_prompt = f"Here are the document pages to analyze: {''.join(pages_subset)}"

        # Send request to LLM for structured section extraction
        response = await batch_client._process_single_request(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            json_mode=True,
            model=Config.GPT_GENERATION_4i,
            convert_to_json=True
        )

        # Return structured sections and model token usage details
        return (
            SectionExtraction(sections=response.content),
            response.input_tokens,
            response.output_tokens,
            response.model
        )

    except Exception as e:
        log_with_span(
            "Section extraction failed",
            "SectionExtractionError",
            "error",
            log_extra={
                "service_name": "section extraction",
                "status": "Failed",
                "input": {"index_start": index.start_page,
                "index_end": index.end_page},
                "error": str(e)
            }
        )
        raise

async def get_rate_card(file_path: str) -> str:
    """
    Reads an Excel workbook, converts all sheets into Markdown tables, and returns
    the combined Markdown string.

    Args:
        file_path (str): Path to the Excel workbook containing rate card data.
        finance_data (dict): Finance data for context (currently not used in processing).
        terms (dict): Contract terms for context (currently not used in processing).

    Returns:
        str: A Markdown-formatted string combining all sheets from the workbook.

    Notes:
        - Converts percentage-formatted cells to proper percentage strings.
        - Logs key steps: Excel parsing, Markdown conversion, and errors.
    """
    try:
        # ============================================================
        # LOAD EXCEL WORKBOOK
        # ============================================================
        wb = load_workbook(file_path, data_only=True)
        sheets = wb.sheetnames
        excel_data = {}

        # ============================================================
        # PARSE SHEETS INTO DATAFRAMES
        # ============================================================
        for sheet in sheets:
            ws = wb[sheet]
            rows = []

            for row in ws.iter_rows():
                row_values = []
                for cell in row:
                    # Handle percentage formatting
                    if cell.number_format.endswith('%') and isinstance(cell.value, (float, int)):
                        if -1 < cell.value < 1:  # Excel stores percentages as 0-1
                            row_values.append(f"{cell.value * 100}%")
                        else:
                            row_values.append(cell.value)
                    else:
                        row_values.append(cell.value)
                rows.append(row_values)

            # Convert to DataFrame
            df = pd.DataFrame(rows[1:], columns=rows[0])
            excel_data[sheet] = df

        # ============================================================
        # LOG: Excel parsed
        # ============================================================
        log_with_span(
            message="Excel workbook parsed successfully",
            span_name="GetRateCard",
            level="info",
            log_extra={
                "service_name": "Get Rate Card",
                "api_name": "Contract-Negotiation",
                "input": file_path,
                "output": f"Sheets: {list(excel_data.keys())}",
                "status": "excel_parsed",
                "error": None
            }
        )

        # ============================================================
        # CONVERT DATAFRAMES TO MARKDOWN
        # ============================================================
        markdown_output = []

        for sheet_name, df in excel_data.items():
            md_table = df.to_markdown(index=False)
            markdown_output.append(f"## {sheet_name}\n\n{md_table}\n\n---\n")

        final_markdown = "\n".join(markdown_output)

        # ============================================================
        # LOG: Markdown conversion completed
        # ============================================================
        log_with_span(
            message="Markdown conversion completed",
            span_name="GetRateCard",
            level="info",
            log_extra={
                "service_name": "Get Rate Card",
                "api_name": "Contract-Negotiation",
                "input": "Excel dataframes",
                "output": f"Markdown with {len(excel_data)} sheets",  # avoid large payload
                "status": "markdown_ready",
                "error": None
            }
        )

        return final_markdown

    except Exception as e:
        # ============================================================
        # LOG: Fatal error
        # ============================================================
        log_with_span(
            message="Rate card processing failed",
            span_name="GetRateCard",
            level="error",
            log_extra={
                "service_name": "Get Rate Card",
                "api_name": "Contract-Negotiation",
                "input": file_path,
                "output": None,
                "status": "failed",
                "error": str(e)
            }
        )
        raise

async def all_contracts_data() -> Dict[str, str]:
    """
    Reads the 'Finance' sheet from the Contract Negotiation Excel file, 
    filters active work packages, and extracts text from their corresponding PDF contracts asynchronously.

    Returns:
        Dict[str, str]: A dictionary where the key is the work package code and 
                        the value is the combined text from the contract PDF.

    Notes:
        - Assumes PDF files are stored in 'data/contracts/{Work Package Code}.pdf'.
        - Uses the async function `extract_and_join_pages` to read and join PDF content.
        - Only active studies (Study Status = "Active") are processed.
    """

    # ============================================================
    # CONFIGURATION
    # ============================================================
    excel_file = os.path.join(os.getcwd(), "data", "Contract_Negotiation.xlsx")
    sheet_name = "Finance"

    # ============================================================
    # READ EXCEL
    # ============================================================
    df = pd.read_excel(excel_file, sheet_name=sheet_name)

    # Clean column names (strip spaces)
    df.columns = df.columns.str.strip()

    # ============================================================
    # FILTER ACTIVE STUDIES
    # ============================================================
    active_df = df[df["Study Status"].astype(str).str.lower() == "active"]

    # ============================================================
    # GET ALL UNIQUE WORK PACKAGE CODES
    # ============================================================
    work_packages = active_df["Work Package Code"].dropna().unique()

    # ============================================================
    # BUILD CONTRACT PDF PATHS
    # ============================================================
    contracts_paths = [
        (wp, os.path.join(os.getcwd(), "data", "contracts", f"{wp}.pdf"))
        for wp in work_packages
    ]

    # ============================================================
    # PROCESS ALL PDF FILES ASYNCHRONOUSLY
    # ============================================================
    tasks = [
        extract_and_join_pages(wp, path)
        for wp, path in contracts_paths
        if os.path.exists(path)
    ]

    results_list = await asyncio.gather(*tasks)

    # ============================================================
    # CONVERT LIST OF TUPLES TO DICTIONARY
    # ============================================================
    results = {wp: pages for wp, pages in results_list}

    return results


async def extract_and_join_pages(wp: str, pdf_path: str) -> Tuple[str, str]:
    """
    Extracts all pages from a PDF and joins them into a single string.

    Args:
        wp (str): Work package code or identifier.
        pdf_path (str): Path to the PDF file.

    Returns:
        Tuple[str, str]: A tuple containing:
            - Work package code
            - Combined text of all pages in the PDF

    Notes:
        - Uses an async PDF extraction function `extract_pdf_pages`.
        - Logs the extraction process for tracing.
    """
    try:
        # Log start of extraction
        log_with_span(
            f"Extracting PDF: {pdf_path}",
            span_name="ExtractAndJoinPages",
            level="info",
            log_extra={"pdf_path": pdf_path}
        )

        # Call your existing async PDF extractor
        data, duration = await extract_pdf_pages(pdf_path)

        # Join all pages into a single string
        all_pages = "\n".join(page for page in data.pages)

        return wp, all_pages
    except Exception as e:
        pass

async def full_work_package_summary(work_package_code: str) -> WorkPackageSummary:
    """
    Extracts finance, performance, and program summary information for a given work package (WP)
    from the Contract_Negotiation.xlsx source, cleans and formats the data, and returns the
    full summary as markdown wrapped inside a Pydantic model.

    Args:
        work_package_code (str): Work Package (WP) code used to filter Finance & Performance data.

    Returns:
        WorkPackageSummary: A Pydantic model containing 3 markdown sections —
            - finance_markdown
            - performance_markdown
            - program_summary_markdown

    Raises:
        ValueError: If the specified WP code is not found in the Finance sheet.
    """

    # Log
    log_with_span(
        f"WORK PACKAGE: {work_package_code}",
        "FullWorkPackageSummary",
        "info",
        log_extra={"work_package_code": work_package_code}
    )

    # ============================================================
    # LOAD EXCEL
    # ============================================================
    file_path = os.path.join(os.getcwd(), "data", "Contract_Negotiation.xlsx")
    xls = pd.ExcelFile(file_path)

    df_finance_raw = pd.read_excel(xls, sheet_name="Finance")
    df_perf_raw = pd.read_excel(xls, sheet_name="survey_performance")

    # ============================================================
    # CLEAN DATAFRAMES
    # ============================================================
    def clean_df(df: pd.DataFrame) -> pd.DataFrame:
        """Remove empty columns and replace NaN with blank strings."""
        df = df.dropna(axis=1, how="all")
        return df.replace({np.nan: "", None: ""})

    df_finance = clean_df(df_finance_raw)
    df_perf = clean_df(df_perf_raw)

    # ============================================================
    # REQUIRED COLUMNS
    # (filtered based on availability)
    # ============================================================
    finance_cols = [
        "Vendor Proposed (per category)", "Central Lab Vendor Proposed",
        "ECG Vendor Proposed", "Biomarker Vendor Proposed",
        "PR&R Vendor Proposed", "eCOA Vendor Proposed",
        "Imaging Vendor Proposed", "Ancillaries Vendor Proposed",
        "Life time projects costs", "ACT 2022", "ACT 2023", "ACT 2024", "ACT 2025",
        "2023–2036 forecast", "2024–2036 forecast", "2025–2037 forecast", "2026–2038 forecast",
        "Total MSA Savings DISCOUNT Forecast", "Total MSA Savings DISCOUNT Actuals",
        "Bundling Savings Forecast", "Bundling Savings Actual",
        "Operational Savings Forecast", "Operational Savings Actual",
        "Variance", "Total Accelerated Timelines Forecast",
        "Total Accelerated Timelines Actual",
        "Countries Planned / Confirmed", "Sites Planned / Confirmed",
        "Enrollment / Screening / Randomization counts",
        "Number of Third-Party Vendors",
        "Complexity Levels (CSE, Monitoring, Data Mgmt, SP, MedWrit)",
        "Vendor Name", "Work Package Type / Sub Type",
        "Work Package Code", "Data Capture Standards",
        "Number of CRFs, Edit Checks, Data Transfers"
    ]

    performance_cols = [
        "Vendor Name", "Service Name", "Service Category",
        "Performance Satisfaction", "Quality Satisfaction",
        "Adherence Satisfaction", "Comm & Colab Satisfaction",
        "User Satisfaction", "Areas of Improvement",
        "Survey Comments on Dissatisfaction",
        "Active & Qualified by ESPIR",
        "Training Provided to Site Personnel",
        "Training Provided to Site Personnel Comments"
    ]

    finance_cols = [c for c in finance_cols if c in df_finance.columns]
    performance_cols = [c for c in performance_cols if c in df_perf.columns]

    df_finance = df_finance[finance_cols]
    df_perf = df_perf[performance_cols]

    # ============================================================
    # FINANCE FILTER
    # ============================================================
    finance_row = df_finance[df_finance["Work Package Code"] == work_package_code]
   
    finance_row = finance_row.iloc[0]

    vendor_name_clean = str(finance_row.get("Vendor Proposed (per category)", "")).lower().strip()
    service_category_clean = str(finance_row.get("Work Package Type / Sub Type", "")).lower().strip()

    # ============================================================
    # PERFORMANCE FILTER
    # ============================================================
    filtered_perf = df_perf[
        (df_perf["Vendor Name"].str.lower().str.strip() == vendor_name_clean) &
        (df_perf["Service Category"].str.lower().str.strip() == service_category_clean)
    ]

    # ============================================================
    # MARKDOWN HELPERS
    # ============================================================
    def row_to_md(title: str, row: pd.Series) -> str:
        """Convert a single row into markdown list format."""
        md = f"## {title}\n\n"
        for col, val in row.items():
            if val not in ("", None, np.nan):
                md += f"- **{col}**: {val}\n"
        return md + "\n"

    def df_to_md(df: pd.DataFrame, title: str) -> str:
        """Convert a dataframe into a markdown section."""
        md = f"## {title}\n"
        if df.empty:
            return md + "\n_No matching performance records found_\n\n"

        for idx, row in df.iterrows():
            md += f"\n### Record {idx + 1}\n"
            for col, val in row.items():
                if val not in ("", None, np.nan):
                    md += f"- **{col}**: {val}\n"
        return md + "\n"

    finance_md = row_to_md("Finance Data Extract", finance_row)
    performance_md = df_to_md(filtered_perf, "Performance Data Extract")

    # ============================================================
    # PROGRAM SUMMARY
    # ============================================================
    TARGET_WP = work_package_code
    df = df_finance_raw

    target_row = df[df["Work Package Code"] == TARGET_WP].iloc[0]
    TARGET_PROGRAM = target_row["Program Award Name"]
    TARGET_VENDOR = target_row["Vendor Proposed (per category)"]
    TARGET_SERVICE = target_row["Work Package Type / Sub Type"]
    TARGET_COST = target_row["Life time projects costs"]

    valid_status = ["Active", "In Progress", "Upcoming", "Forecasted"]

    df_program_active = df[
        (df["Program Award Name"] == TARGET_PROGRAM) &
        (df["Study Status"].isin(valid_status))
    ]

    program_tcv = df_program_active["Life time projects costs"].sum()

    program_tcv_detail_md = "\n".join([
        f"- **{r['Work Package Code']}** | Vendor: **{r['Vendor Proposed (per category)']}** | "
        f"Service: **{r['Work Package Type / Sub Type']}** | Cost: **{r['Life time projects costs']:,.0f}**"
        for _, r in df_program_active.iterrows()
    ])

    df_vendor_active = df[
        (df["Vendor Proposed (per category)"] == TARGET_VENDOR) &
        (df["Study Status"].isin(valid_status))
    ]

    vendor_tcv_active = df_vendor_active["Life time projects costs"].sum()

    vendor_tcv_detail_md = "\n".join([
        f"- Program: **{r['Program Award Name']}** | WP: **{r['Work Package Code']}** | "
        f"Service: **{r['Work Package Type / Sub Type']}** | Cost: **{r['Life time projects costs']:,.0f}**"
        for _, r in df_vendor_active.iterrows()
    ])

    program_summary_md = f"""
# Program Summary: **{TARGET_PROGRAM}**

**Total Active Work Packages in Program**: {len(df_program_active)}

---

## Active Work Packages in this Program
{program_tcv_detail_md}
- **Total Program TCV**: {program_tcv:,.0f}

---

## Vendor Leverage Across All Active Work Packages
### Vendor: **{TARGET_VENDOR}**
### Total {TARGET_VENDOR} Active TCV (Vendor Leverage): **{vendor_tcv_active:,.0f}**
**Detailed Breakdown (Only Active WPs by this Vendor):**
{vendor_tcv_detail_md}

---

## Current Target Work Package (For Negotiation)
## Target Work Package Snapshot
- **Work Package Code**: {TARGET_WP}
- **Vendor**: {TARGET_VENDOR}
- **Service**: {TARGET_SERVICE}
- **Cost**: {TARGET_COST:,.0f}

"""

    # ============================================================
    # RETURN — Wrapped in Pydantic model
    # ============================================================
    return WorkPackageSummary(
        finance_markdown=finance_md,
        performance_markdown=performance_md,
        program_summary_markdown=program_summary_md
    )


async def get_vendor_key_from_finance(wp: str) -> VendorFinanceInfo:
    """
    Extract vendor, work package type, contract value, and discount value
    for a given work package code from the Finance sheet of the Contract Negotiation Excel file.

    Args:
        wp (str): Work Package code to filter in the Finance sheet.

    Returns:
        VendorFinanceInfo: Pydantic model containing vendor info, WP type, contract value, and discount.

    Raises:
        ValueError: If the given work package code is not found in the Finance sheet.
    """

    # ============================================================
    # Excel path
    # ============================================================
    excel_path = os.path.join(os.getcwd(), "data", "Contract_Negotiation.xlsx")

    # Load Finance sheet
    df = pd.read_excel(excel_path, sheet_name="Finance")

    # Filter by Work Package Code
    row = df[df["Work Package Code"] == wp]

    row = row.iloc[0]

    # ============================================================
    # Extract needed columns
    # ============================================================
    wp_type = str(row.get("Work Package Type / Sub Type", "")).strip()
    vendor = str(row.get("Vendor Proposed (per category)", "")).strip()

    # Contract value & discount
    contract_value = row.get("Life time projects costs", 0)
    discount_value = row.get("Total MSA Savings DISCOUNT Actuals", 0)

    # Convert NaN to 0
    contract_value = 0.0 if pd.isna(contract_value) else float(contract_value)
    discount_value = 0.0 if pd.isna(discount_value) else float(discount_value)

    # ============================================================
    # Return wrapped in Pydantic model
    # ============================================================
    return VendorFinanceInfo(
        vendor_name=vendor,
        work_package_type=wp_type,
        contract_value=contract_value,
        discount_value=discount_value
    )
